---
dependency:
  name: galaxy

driver:
  name: docker

provisioner:
  name: ansible
  # log: true

verifier:
  name: ansible

scenario:
  name: default

platforms:
  - name: redhat-8
    image: registry.access.redhat.com/ubi8/ubi

  - name: centos-8
    image: centos:8

  - name: ubuntu-21.04
    image: ubuntu:21.04

    # 10
  - name: debian-buster
    image: debian:buster
