---
name: Develop branch workflow

on:
  push:
    branches:
      - develop
    paths-ignore:
      - "**.md"

  pull_request:
    branches:
      - develop
    paths-ignore:
      - "**.md"

env:
  GITHUB_ROLE_NAME: ansible-role-awscli
  GALAXY_ROLE_NAME: christiangda.awscli

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [2.7, 3.5, 3.6, 3.7, 3.8]
        ansible: [">=2.9,<2.10", ">=2.10,<2.11"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python: ${{ matrix.python }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible"${{ ANSIBLE_VERSION} }}"
          pip install molecule
          pip install docker
          pip install 'molecule[docker]'
          pip install flake8
          pip install selinux
          pip install docker
          pip install pylint
          pip install rope
          pip install ansible-lint

      - name: Preparing the role
        run: |
          ls -la
          cd ../
          ls -la
          mv ${{ GITHUB_ROLE_NAME }} ${{ GALAXY_ROLE_NAME }}
          cd ${{ GALAXY_ROLE_NAME }}
          ls -la

      - name: Show versions
        run: |
          molecule --version
          ansible --version

      - name: Show versions
        run: |
          molecule test --scenario-name default
