---
dependency:
  name: galaxy

driver:
  name: docker

provisioner:
  name: ansible
  # log: true

verifier:
  name: ansible

scenario:
  name: default

platforms:
  - name: ubuntu-21.04
    image: ubuntu:21.04
